
spring.application.name=taskflow
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=1065792324491-qn8vjoll0htf065hobnl2mjtduga37j5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/calendar
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google